export const COMMAND1_LIST_REQUEST = 'COMMAND1_LIST_REQUEST'
export const COMMAND1_LIST_SUCCESS = 'COMMAND1_LIST_SUCCESS'
export const COMMAND1_LIST_FAIL = 'COMMAND1_LIST_FAIL'

export const COMMAND2_LIST_REQUEST = 'COMMAND2_LIST_REQUEST'
export const COMMAND2_LIST_SUCCESS = 'COMMAND2_LIST_SUCCESS'
export const COMMAND2_LIST_FAIL = 'COMMAND2_LIST_FAIL'


export const COMMAND3_LIST_REQUEST = 'COMMAND3_LIST_REQUEST'
export const COMMAND3_LIST_SUCCESS = 'COMMAND3_LIST_SUCCESS'
export const COMMAND3_LIST_FAIL = 'COMMAND3_LIST_FAIL'


export const COMMAND4_LIST_REQUEST = 'COMMAND4_LIST_REQUEST'
export const COMMAND4_LIST_SUCCESS = 'COMMAND4_LIST_SUCCESS'
export const COMMAND4_LIST_FAIL = 'COMMAND4_LIST_FAIL'